name: Test Not Found Action

on:
  workflow_dispatch:

jobs:
  test_not_found_with_failure:
   runs-on: ubuntu-latest
   name: Extract Payload
   
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Parse Issue Body
       uses: ./
       id: issue_body_parser
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         issue_id: 1
         payload_marker: invalid_marker

  test_not_found_without_failure:
    runs-on: ubuntu-latest
    name: Extract Payload
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Parse Issue Body
        uses: ./
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: 1
          fail_on_missing: false
          payload_marker: invalid_marker